title: "Laravelのススメ"
summary: "
本書で取り扱うこと\n
\n
・Dockerを使ったLaravelの開発環境の構築\n
・セキュリティ\n
・プロジェクト構造\n
\n
本書で取り扱わないこと\n
・PHPの基礎文法\n
・JavaScript/TypeScriptの基礎文法\n
・HTTPについての基礎的な説明\n
\n
本書の対象読者\n
・一通りのプログラミング経験がある方\n
・Webフレームワークを使った開発経験がある方\n
"
topics: ['laravel', 'ベストプラクティス', 'PHP']
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - preface
  - preparing-environment
  - system-requirement
  - setting-database
  - setting-routing
