title: "Laravelのススメ"
summary: "
Laravel 初学者向けに Laravel を使った開発の方法やベストプラクティスの解説をします。\n

「PHPはなんとなく触ったことがあるけど、Laravel のことは全然知らない」、「Webフレームワークを使ったことがない」という方が、実際に開発を進めながら Laravel の知識を深めていけるようになっています。\n

誤字脱字やわかりにくい部分があったという方がいれば、気兼ねなくコメントで教えていただけると幸いです。
"
topics: ['laravel', 'ベストプラクティス', 'PHP']
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - what-is-web-framework
  - preparing-environment
